# Generated by Django 3.0.11 on 2020-11-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20201121_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='badge_image',
            field=models.ImageField(upload_to='badges/', verbose_name='Badge'),
        ),
        migrations.AlterField(
            model_name='user',
            name='badges',
            field=models.ManyToManyField(blank=True, related_name='users', to='user.Badge'),
        ),
    ]
