# Generated by Django 3.0.11 on 2020-11-30 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20201127_0442'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
