# Generated by Django 3.0.11 on 2020-12-04 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follower', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='followers',
            new_name='follower',
        ),
    ]
